[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    " set signcolumn=yes
    set updatetime=100
'''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
    nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = 'InsertEnter'
hook_source = '''
  source $HOME/go/src/github.com/kazukousen/dotfiles/nvim/dein/ddc.vim
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source ='ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source ='ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source ='ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source ='ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source ='ddc.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'


