[[plugins]]
repo = 'Shougo/dein.vim'

# show git-diff visualization on left-side
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    " set signcolumn=yes
    set updatetime=100
'''

# colorscheme
# :call dein#recache_runtimepath()
[[plugins]] # unused
repo = 'joshdick/onedark.vim'
hook_add = '''
  " colorscheme onedark
'''
[[plugins]] # unused
repo = 'jnurmine/Zenburn'
hook_add = '''
  " colorscheme zenburn
'''
[[plugins]] # unused
repo = 'morhetz/gruvbox'
hook_add = '''
  " let g:gruvbox_contrast_dark = 'soft'
  " colorscheme gruvbox
'''
[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
  let g:gruvbox_material_background = 'soft'
  colorscheme gruvbox-material
'''
# [[plugins]]
# repo = 'savq/melange'
# hook_add = '''
#   set termguicolors
#   colorscheme melange
# '''
# [[plugins]]
# repo = 'junegunn/seoul256.vim'
# hook_add = '''
#  let g:seoul256_background = 235
#  colorscheme seoul256
#  set background=dark
# '''

# code highlight
[[plugins]]
repo = 'sheerun/vim-polyglot'

# filer
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  nnoremap <C-n> :Fern . -reveal=%<CR>

  " show hidden files
  let g:fern#default_hidden = 1
  " exclude to show files
  " https://github.com/lambdalisue/fern.vim/issues/233
  let hide_dirs = '^\%(\.git\)$'
  let hide_files = '\%(\.DS_Store\)\+'
  let g:fern#default_exclude = hide_dirs . '\|' . hide_files
'''

# fern + git visualization
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

# template/snipet
[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '$HOME/go/src/github.com/kazukousen/dotfiles/nvim/dein/sonictemplate'
'''

# search
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = 0

# depends ripgrep
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))

  nnoremap <silent> <C-f> :Rg<CR>
'''

# show buffers like tabs
[[plugins]]
repo = 'ap/vim-buftabline'
hook_add = '''
  nnoremap <silent> J :bprev<CR>
  nnoremap <silent> K :bnext<CR>
  nnoremap <silent> <C-w> :bw<CR>
'''

# completion
[[plugins]]
repo = "neoclide/coc.nvim"
rev = "release"
merged = '0'
hook_add = '''
  let g:coc_global_extensions = [
  \ 'coc-go',
  \ 'coc-rust-analyzer'
  \]
'''

