[[plugins]]
repo = 'Shougo/dein.vim'

# show git-diff visualization on left-side
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    " set signcolumn=yes
    set updatetime=100
'''

# colorscheme
# :call dein#recache_runtimepath()
[[plugins]]
repo = 'junegunn/seoul256.vim'
hook_add = '''
  colorscheme seoul256
  set background=dark
'''
# [[plugins]]
# repo = 'joshdick/onedark.vim'
# hook_add = '''
#   colorscheme onedark
# '''

# code highlight
[[plugins]]
repo = 'sheerun/vim-polyglot'

# filer
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  nnoremap <C-n> :Fern . -reveal=%<CR>

  " show hidden files
  let g:fern#default_hidden=1
'''

# fern + git visualization
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

# template/snipet
[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_add = '''
  let g:sonictemplate_vim_template_dir = '$HOME/go/src/github.com/kazukousen/dotfiles/nvim/dein/sonictemplate'
'''

# search
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = 0

# depends ripgrep
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))

  nnoremap <silent> <C-f> :Rg<CR>
'''

# show buffers like tabs
[[plugins]]
repo = 'ap/vim-buftabline'
hook_add = '''
  nnoremap <silent> J :bprev<CR>
  nnoremap <silent> K :bnext<CR>
  nnoremap <silent> <C-w> :bw<CR>
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = 'InsertEnter'
hook_source = '''
  source $HOME/go/src/github.com/kazukousen/dotfiles/nvim/dein/ddc.vim
'''

# existing words in around
[[plugins]]
repo = 'Shougo/ddc-around'
on_source ='ddc.vim'

# file name
[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source ='ddc.vim'

# word being entered
[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source ='ddc.vim'

# sort
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source ='ddc.vim'

# remove duplicated
[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source ='ddc.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

