[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    " set signcolumn=yes
    set updatetime=100
'''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
    nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

